<a href="https://colab.research.google.com/github/gio-remo/Workbook/blob/main/Python/02_data-analytics-python/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### L9 - Numpy Arrays

In [9]:
import numpy as np

In [11]:
np.array([1,2,3])

array([1, 2, 3])

In [13]:
x = np.array([4,5,6])
x

array([4, 5, 6])

In [15]:
x[0] + x[1]

9

In [17]:
x[-1]

6

In [19]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
m.shape, m.size

((2, 3), 6)

In [21]:
m[0][1], m[0,1]

(2, 2)

In [25]:
m.sum()

21

In [26]:
m.mean()

3.5

In [27]:
m.std()

1.707825127659933

### L10 - Numpy Operations

In [29]:
y = np.arange(5) # return evenly spaced values within a given interval
y

array([0, 1, 2, 3, 4])

In [30]:
y + 10

array([10, 11, 12, 13, 14])

### L11 - Numpy Boolean Arrays

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a[[0,-1]] # multi index

array([0, 4])

In [37]:
a > 2

array([False, False, False,  True,  True])

In [38]:
a[a>2]

array([3, 4])

In [39]:
a.mean()

2.0

In [40]:
a[a >= a.mean()]

array([2, 3, 4])